// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1) {
  return window['go']['DataAdmin']['DataAdmin']['Close'](arg1);
}

export function Connect(arg1) {
  return window['go']['DataAdmin']['DataAdmin']['Connect'](arg1);
}

export function Execute(arg1, arg2) {
  return window['go']['DataAdmin']['DataAdmin']['Execute'](arg1, arg2);
}

export function GetJSONschema(arg1) {
  return window['go']['DataAdmin']['DataAdmin']['GetJSONschema'](arg1);
}

export function GetTableSchema(arg1) {
  return window['go']['DataAdmin']['DataAdmin']['GetTableSchema'](arg1);
}

export function JSONQuery(arg1, arg2) {
  return window['go']['DataAdmin']['DataAdmin']['JSONQuery'](arg1, arg2);
}

export function Query(arg1, arg2) {
  return window['go']['DataAdmin']['DataAdmin']['Query'](arg1, arg2);
}
