// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {DataAdmin} from '../models';
import {sql} from '../models';

export function Close(arg1:string):Promise<void>;

export function Connect(arg1:DataAdmin.ConnectionSettings):Promise<string>;

export function Execute(arg1:string,arg2:string):Promise<sql.Result>;

export function GetJSONschema(arg1:string):Promise<string>;

export function GetTableSchema(arg1:string):Promise<Record<string, Array<DataAdmin.ColumnMeta>>>;

export function JSONQuery(arg1:string,arg2:string):Promise<string>;

export function Query(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;
