// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPUInfo() {
  return window['go']['sysmon']['SystemMonitor']['GetCPUInfo']();
}

export function GetDiskInfo(arg1) {
  return window['go']['sysmon']['SystemMonitor']['GetDiskInfo'](arg1);
}

export function GetGPUInfo() {
  return window['go']['sysmon']['SystemMonitor']['GetGPUInfo']();
}

export function GetNetworkInfo() {
  return window['go']['sysmon']['SystemMonitor']['GetNetworkInfo']();
}

export function GetRAMInfo() {
  return window['go']['sysmon']['SystemMonitor']['GetRAMInfo']();
}

export function HostInfo() {
  return window['go']['sysmon']['SystemMonitor']['HostInfo']();
}
