// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sysmon} from '../models';

export function GetCPUInfo():Promise<sysmon.CPUInfo>;

export function GetDiskInfo(arg1:string):Promise<sysmon.DiskInfo>;

export function GetGPUInfo():Promise<sysmon.GPUInfo>;

export function GetNetworkInfo():Promise<sysmon.NetworkInfo>;

export function GetRAMInfo():Promise<sysmon.RAMInfo>;

export function HostInfo():Promise<string|string>;
