// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteRemoteCommand(arg1, arg2) {
  return window['go']['sysagent']['SysAgent']['ExecuteRemoteCommand'](arg1, arg2);
}

export function GetDeviceInfoStub() {
  return window['go']['sysagent']['SysAgent']['GetDeviceInfoStub']();
}

export function GetDevices() {
  return window['go']['sysagent']['SysAgent']['GetDevices']();
}

export function GetHistory(arg1) {
  return window['go']['sysagent']['SysAgent']['GetHistory'](arg1);
}

export function SendCommand(arg1, arg2) {
  return window['go']['sysagent']['SysAgent']['SendCommand'](arg1, arg2);
}

export function Start() {
  return window['go']['sysagent']['SysAgent']['Start']();
}

export function Stop() {
  return window['go']['sysagent']['SysAgent']['Stop']();
}
