// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sysagent} from '../models';

export function ExecuteRemoteCommand(arg1:string,arg2:string):Promise<string>;

export function GetDeviceInfoStub():Promise<sysagent.DeviceInfo>;

export function GetDevices():Promise<Record<string, sysagent.DeviceInfo>>;

export function GetHistory(arg1:string):Promise<sysagent.History>;

export function SendCommand(arg1:string,arg2:string):Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
